# This file was generated by the {rix} R package v0.18.1 on 2026-02-08
# with following call:
# >rix(r_ver = "4.5.1",
#  > r_pkgs = c("curl",
#  > "jsonlite",
#  > "stringr",
#  > "tidyRSS",
#  > "pkgsearch",
#  > "lubridate",
#  > "magrittr",
#  > "commonmark",
#  > "xml2",
#  > "tibble",
#  > "purrr",
#  > "rstudioapi",
#  > "dplyr",
#  > "ggplot2",
#  > "bslib",
#  > "shiny",
#  > "officer",
#  > "chromote",
#  > "tidyr",
#  > "glue"),
#  > system_pkgs = c("quarto",
#  > "chromium",
#  > "curl",
#  > "imagemagick"),
#  > git_pkgs = list(list(package_name = "rweekly.tools",
#  > repo_url = "https://github.com/rweekly/rweekly.tools/",
#  > branch_name = "master",
#  > commit = "7a1c7c7802b841ad086083211e48b922b4bfefb3"),
#  > list(package_name = "rweekly.highlights",
#  >      repo_url = "https://github.com/rweekly/rweekly.highlights",
#  > branch_name = "master",
#  > commit = "52fac2c934e9597515de0b3f7f6bf139f4af931a")),
#  > ide = "none",
#  > project_path = ".",
#  > overwrite = TRUE)
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2025-10-27.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      bslib
      chromote
      commonmark
      curl
      dplyr
      ggplot2
      glue
      jsonlite
      lubridate
      magrittr
      officer
      pkgsearch
      purrr
      rstudioapi
      shiny
      stringr
      tibble
      tidyr
      tidyRSS
      xml2;
  };
 
    rweekly.highlights = (pkgs.rPackages.buildRPackage {
      name = "rweekly.highlights";
      src = pkgs.fetchgit {
        url = "https://github.com/rweekly/rweekly.highlights";
        rev = "52fac2c934e9597515de0b3f7f6bf139f4af931a";
        sha256 = "sha256-B4Ewj1KeKSBp3HNiahszAgD45XmfK5hZ9PTzBULNYYg=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) 
          magrittr
          stringr
          httr
          shiny
          xml2
          commonmark
          fs
          purrr
          golem
          bslib
          config;
      };
    });

    rweekly.tools = (pkgs.rPackages.buildRPackage {
      name = "rweekly.tools";
      src = pkgs.fetchgit {
        url = "https://github.com/rweekly/rweekly.tools/";
        rev = "7a1c7c7802b841ad086083211e48b922b4bfefb3";
        sha256 = "sha256-3es0zQzfRPskoe/RVD9yXTLbnkrvVTBEtwHviI7YEAs=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) 
          dplyr
          magrittr
          httr
          git2r
          magick
          stringr;
      };
    });
      
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      chromium
      curl
      glibcLocales
      imagemagick
      nix
      quarto
      R;
  };
  
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.stdenv.hostPlatform.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    
    buildInputs = [ rweekly.tools rweekly.highlights rpkgs system_packages ];
    
  }; 
in
  {
    inherit pkgs shell;
  }
