[
  {
    "title": "How to pick up 3 numbers from a uniform distribution in a transparent manner?",
    "href": "https://feedproxy.google.com/~r/ChristopheLadroueR/~3/sRTOQCTSldc/"
  },
  {
    "title": "Bedtools tutorial from 2013 CSHL course",
    "href": "http://www.gettinggeneticsdone.com/2014/06/bedtools-tutorial-from-2013-cshl-course.html"
  },
  {
    "title": "MCMskv #2 [ridge with a view]",
    "href": "https://xianblog.wordpress.com/2016/01/07/mcmskv-2-ridge-with-a-view/"
  },
  {
    "title": "reproducible logo generated by ggtree",
    "href": "http://guangchuangyu.github.io/2016/10/reproducible-logo-generated-by-ggtree/"
  },
  {
    "title": "Generosity of Asian Central Banks",
    "href": "http://timelyportfolio.blogspot.com/2011/10/generosity-of-asian-central-banks.html"
  },
  {
    "title": "A Weekend With Julia: An R User’s Reflections",
    "href": "http://www.econometricsbysimulation.com/2014/04/a-weekend-with-julia-r-users-reflections.html"
  },
  {
    "title": "Review: Kölner R Meeting 12 April 2013",
    "href": "http://www.magesblog.com/2013/04/review-kolner-r-meeting-12-april-2013.html"
  },
  {
    "title": "A Preview of My Talk for the Data Science Africa Workshop organized by the United Nations",
    "href": "http://blog.danielemaasit.com/2016/06/28/a-preview-of-my-talk-for-the-data-science-africa-workshop-organized-by-the-united-nations/"
  },
  {
    "title": "“An R package” or “A R package”",
    "href": "https://csgillespie.wordpress.com/2011/03/26/an-r-package-or-a-r-package/"
  },
  {
    "title": "A Return.Portfolio Wrapper to Automate Harry Long Seeking Alpha Backtests",
    "href": "https://quantstrattrader.wordpress.com/2016/06/17/a-return-portfolio-wrapper-to-automate-harry-long-seeking-alpha-backtests/"
  },
  {
    "title": "Namespaces and name conflicts",
    "href": "https://brokeringclosure.wordpress.com/2010/08/31/namespaces-and-name-conflicts/"
  },
  {
    "title": "My R setup with Mac OS X",
    "href": "http://www.milktrader.net/2011/02/my-r-setup-with-mac-os-x.html"
  },
  {
    "title": "ECG Signal Processing",
    "href": "http://biostatmatt.com/archives/78"
  },
  {
    "title": "Inference for MA(q) Time Series",
    "href": "http://freakonometrics.hypotheses.org/12214"
  },
  {
    "title": "Image Manipulation in R, Part 1",
    "href": "http://is-r.tumblr.com/post/36586614678/image-manipulation-in-r-part-1"
  },
  {
    "title": "R Function of the Day: foodweb",
    "href": "https://web.archive.org/web/http://www.sigmafield.org/2010/09/21/r-function-of-the-day-foodweb"
  },
  {
    "title": "52 Vis Week 1 Winners!",
    "href": "http://rud.is/b/2016/04/13/52-vis-week-1-winners/"
  },
  {
    "title": "R Markdown Tutorial by RStudio and DataCamp",
    "href": "https://www.datacamp.com/community/blog/r-markdown-tutorial-reproducible-reporting-in-r"
  },
  {
    "title": "R Basics at Simple Talk",
    "href": "http://www.r-chart.com/2015/03/r-basics-at-simple-talk.html"
  },
  {
    "title": "RStan: Fast, multilevel Bayesian modeling in R",
    "href": "http://blog.revolutionanalytics.com/2012/08/rstan-fast-multilevel-bayesian-modeling-in-r.html"
  },
  {
    "title": "An R function to determine if you are a data scientist",
    "href": "http://simplystatistics.tumblr.com/post/11271228367/datascientist"
  },
  {
    "title": "Support Vector Machines in R (a course by Lutz Hamel)",
    "href": "https://web.archive.org/web/http://www.statistics.com/svm?utm_source=r-blogger&utm_medium=website&utm_campaign=svm-r"
  },
  {
    "title": "A brainfuck interpreter for R",
    "href": "https://4dpiecharts.com/2013/04/24/a-brainfuck-interpreter-for-r/"
  },
  {
    "title": "Stop! (In the name of a sensible interface)",
    "href": "https://4dpiecharts.com/2011/08/12/stop-in-the-name-of-a-sensible-interface/"
  },
  {
    "title": "Mining for relations between nominal variables",
    "href": "https://rforwork.info/2012/05/02/mining-for-relations-between-nominal-variables/"
  },
  {
    "title": "More colour wheels",
    "href": "http://www.stubbornmule.net/2011/11/more-colour-wheels/"
  },
  {
    "title": "Notes from A Recent Spatial R Class I Gave",
    "href": "http://davenportspatialanalytics.squarespace.com/blog/2012/6/19/notes-from-a-recent-spatial-r-class-i-gave.html"
  },
  {
    "title": "RInside release 0.1.1, and a fresh example",
    "href": "http://dirk.eddelbuettel.com/blog/2009/09/29/"
  },
  {
    "title": "Hold on to your hats: it’s World Statistics Day!",
    "href": "http://blog.revolutionanalytics.com/2010/10/hold-on-to-your-hats-its-world-statistics-day.html"
  },
  {
    "title": "ABC on wordpress",
    "href": "https://xianblog.wordpress.com/2011/11/08/abc-on-wordpress/"
  },
  {
    "title": "Stop Sign Project Post1: Some GIS stuff done in R",
    "href": "https://r-norberg.blogspot.com/2013/02/stop-sign-project-post1-some-gis-stuff.html"
  },
  {
    "title": "Free one-day R course at Vanderbilt",
    "href": "http://www.gettinggeneticsdone.com/2009/05/free-one-day-r-course-at-vanderbilt.html"
  },
  {
    "title": "Michael Kane on Bigmemory",
    "href": "https://joshpaulson.wordpress.com/2010/12/20/michael-kane-on-bigmemory/"
  },
  {
    "title": "Quantitative Finance Applications in R – 3: Plotting xts Time Series",
    "href": "http://blog.revolutionanalytics.com/2014/01/quantitative-finance-applications-in-r-plotting-xts-time-series.html"
  },
  {
    "title": "Checking validation statistics (Monitor function 030220139)",
    "href": "http://nir-quimiometria.blogspot.com/2013/02/checking-validation-statistics-monitor.html"
  },
  {
    "title": "Ruin probability and infinite time",
    "href": "http://blog.free.fr/"
  },
  {
    "title": "Introduction to OpenCPU for R on EC2 with Python",
    "href": "http://www.joyofdata.de/blog/introduction-to-opencpu-for-r-on-ec2-with-python/"
  },
  {
    "title": "All you need is text – Markdown (via pandoc) for academia",
    "href": "http://www.surefoss.org/publishing-publizieren/all-you-need-is-text-markdown-via-pandoc-for-academia/"
  },
  {
    "title": "curl 0.4 bugfix release",
    "href": "https://www.opencpu.org/posts/curl-release-0-4/"
  },
  {
    "title": "Here comes the sun",
    "href": "https://procomun.wordpress.com/2011/05/02/here-comes-the-sun-3/"
  },
  {
    "title": "As a Data Scientist it is my Obligation to support #nobagida, #nopegida and any other #no[a-z]{2}gida today :)",
    "href": "http://www.joyofdata.de/blog/as-a-data-scientist-it-is-my-obligation-to-support-nobagida-nopegida-and-any-other-noa-z2gida-today/"
  },
  {
    "title": "New Release of ROracle posted to CRAN",
    "href": "https://blogs.oracle.com/R/entry/oracle_advanced_analytics_option_and"
  },
  {
    "title": "Use little images as the markers in a scatterplot",
    "href": "https://robertgrantstats.wordpress.com/2012/10/17/use-little-images-as-the-markers-in-a-scatterplot/"
  },
  {
    "title": "Are Turbocharged Engines More Fuel Efficient?",
    "href": "http://scweiss.blogspot.com/2016/01/does-turbocharging-engines-reduce-fuel.html"
  },
  {
    "title": "New StackOverflow site for Statistics",
    "href": "http://blog.revolutionanalytics.com/2010/07/new-stackoverflow-site-for-statistics.html"
  },
  {
    "title": "Some Impressions from R Finance 2016",
    "href": "http://blog.revolutionanalytics.com/2016/05/r-finance-2016.html"
  },
  {
    "title": "John Chambers recounts the history of S and R",
    "href": "http://blog.revolutionanalytics.com/2014/01/john-chambers-recounts-the-history-of-s-and-r.html"
  },
  {
    "title": "New R User Groups in Europe",
    "href": "http://blog.revolutionanalytics.com/2011/02/new-r-user-groups-in-europe.html"
  },
  {
    "title": "Random sudokus [test]",
    "href": "https://xianblog.wordpress.com/2010/05/18/random-sudokus-test/"
  },
  {
    "title": "New R User Group in Kassel, Germany",
    "href": "http://blog.revolutionanalytics.com/2010/06/new-r-user-group-in-kassel-germany.html"
  }
]
