name: curatinator

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Manual trigger'  
  schedule:
    - cron: '0 9 * * 6' # At 09:00 on Saturday UTC

jobs:
  auto-collect-content:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::tidyverse 
            any::tidyRSS
            any::urltools
            any::pkgsearch

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Collect content
        run: Rscript -e 'source("scripts/curatinator.R")'

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add curatinator_latest.md
          git commit -m 'Auto-collected data updated' || echo "No changes to commit"
          git push origin || echo "No changes to commit"